apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-sample-app
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/hello-fun.git
      ref:
        branch: main
